/**
 * Session Recap Extension
 *
 * After each agent response, injects a subtle footer showing:
 *   ✻ Done in 55s  ※ recap: what was done + what's next  (disable: /config recaps off)
 *
 * Recap text is generated by the cheapest available model (free Kimi → unlimited Kimi → Haiku).
 * Falls back to timing-only if no model is available or the call times out.
 *
 * Commands:
 *   /config recaps        Show current state
 *   /config recaps on     Enable recaps (default)
 *   /config recaps off    Disable recaps
 */

import { complete } from "@earendil-works/pi-ai";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Text } from "@earendil-works/pi-tui";
import {
	getRoleValue,
	ROLE_SPECS,
	resolveRoleCandidates,
	scopeModels,
	setRoleValue,
} from "./_shared/model-roles.ts";

// Recap helper models come from the central "recap" role (configure via /config).
// ctx.model is the guaranteed-authed backstop, appended at call time.

const RECAP_TIMEOUT_MS = 10_000;
const MAX_RECAP_TOKENS = 80;

function formatDuration(ms: number): string {
	if (ms < 1000) return "<1s";
	const s = Math.round(ms / 1000);
	if (s < 60) return `${s}s`;
	const m = Math.floor(s / 60);
	const rem = s % 60;
	return rem > 0 ? `${m}m ${rem}s` : `${m}m`;
}

function buildSnippet(messages: any[]): string {
	const lines: string[] = [];
	for (const msg of messages) {
		const role = msg?.role;
		const content = msg?.content;
		if (!role || !content) continue;

		if (role === "user") {
			const text =
				typeof content === "string"
					? content
					: Array.isArray(content)
						? content
								.filter((c: any) => c?.type === "text")
								.map((c: any) => c.text)
								.join("\n")
						: "";
			if (text.trim()) lines.push(`User: ${text.slice(0, 600).trim()}`);
		} else if (role === "assistant") {
			const parts = Array.isArray(content) ? content : [];
			const text = parts
				.filter((c: any) => c?.type === "text")
				.map((c: any) => c.text)
				.join("\n");
			const toolNames = parts
				.filter((c: any) => c?.type === "toolCall")
				.map((c: any) => String(c.name));
			if (text.trim()) lines.push(`Assistant: ${text.slice(0, 400).trim()}`);
			if (toolNames.length > 0) lines.push(`Tools used: ${toolNames.join(", ")}`);
		}
	}
	return lines.join("\n\n");
}

const RECAP_DELAY_MS = 3 * 60 * 1000; // 3 minutes of inactivity before showing recap

export default function (pi: ExtensionAPI) {
	let enabled = true;
	let hintShown = false;
	let requestStart = 0;
	let pendingTimer: ReturnType<typeof setTimeout> | null = null;
	let pendingMessages: any[] | null = null;
	let pendingElapsed = 0;

	// Restore toggle preference from session history
	pi.on("session_start", (_event, ctx) => {
		for (const entry of ctx.sessionManager.getEntries()) {
			if (entry.type === "custom" && (entry as any).customType === "recap-config") {
				enabled = (entry as any).data?.enabled ?? true;
			}
		}
	});

	pi.on("agent_start", () => {
		requestStart = Date.now();
		// Cancel any pending recap since the user is active again
		if (pendingTimer) {
			clearTimeout(pendingTimer);
			pendingTimer = null;
			pendingMessages = null;
		}
	});

	pi.on("agent_end", (event, ctx) => {
		if (!enabled) return;
		const elapsed = requestStart > 0 ? Date.now() - requestStart : 0;

		// Cancel any existing pending timer and restart the debounce
		if (pendingTimer) {
			clearTimeout(pendingTimer);
		}

		pendingMessages = event.messages;
		pendingElapsed = elapsed;

		pendingTimer = setTimeout(() => {
			pendingTimer = null;
			const messages = pendingMessages;
			pendingMessages = null;
			if (!messages) return;

			void (async () => {
				try {
				const doneStr = `✻ Done in ${formatDuration(pendingElapsed)}`;
				let recap = "";

				try {
					const snippet = buildSnippet(messages);
					if (snippet.trim()) {
						// Cheap configured models first, then the active model as a
						// guaranteed-authed backstop. De-dupe to avoid retrying one.
						const candidates: any[] = [];
						const seen = new Set<string>();
						const add = (m: any) => {
							if (!m) return;
							const key = `${m.provider}/${m.id}`;
							if (seen.has(key)) return;
							seen.add(key);
							candidates.push(m);
						};
						for (const { provider, id } of resolveRoleCandidates("recap")) add(ctx.modelRegistry.find(provider, id));
						add(ctx.model);

						for (const model of candidates) {
							try {
								const auth = await ctx.modelRegistry.getApiKeyAndHeaders(model);
								if (!auth.ok || !auth.apiKey) continue;

								const response = await complete(
									model,
									{
										messages: [
											{
												role: "user",
												content: [
													{
														type: "text",
														text: `Summarize in 1 sentence (max 140 chars, no preamble): what the user asked, what was done, and what's next.\n\n${snippet}`,
													},
												],
												timestamp: Date.now(),
											},
										],
									},
									{
										apiKey: auth.apiKey,
										headers: (auth as any).headers,
										maxTokens: MAX_RECAP_TOKENS,
										signal: AbortSignal.timeout(RECAP_TIMEOUT_MS),
									},
								);

								recap = response.content
									.filter((c): c is { type: "text"; text: string } => c.type === "text")
									.map((c) => c.text)
									.join(" ")
									.trim();

								if (recap) break;
							} catch {
								// Try next model
							}
						}
					}
				} catch {
					// No recap on failure — timing-only fallback below
				}

				const hint = hintShown ? "" : " (disable: /config recaps off)";
				if (recap) hintShown = true;
				const content = recap ? `${doneStr}  ※ recap: ${recap}${hint}` : doneStr;
				pi.sendMessage({ customType: "session-recap", content, display: true });
				} catch {
					// Context went stale (session switch/reload/fork) — silently discard
				}
			})();
		}, RECAP_DELAY_MS);
	});

	// Minimal single-line renderer — subtle, no background box
	pi.registerMessageRenderer("session-recap", (message, _options, theme) => {
		return new Text(theme.fg("dim", String(message.content ?? "")), 0, 0);
	});

	// /config — central interactive config menu.
	//   /config                 open the menu (recaps toggle + model-role pickers)
	//   /config recaps on|off    keep the quick text toggle for muscle memory
	const AUTO_LABEL = "Auto (use defaults)";

	async function pickModelForRole(roleIndex: number, ctx: any): Promise<void> {
		const spec = ROLE_SPECS[roleIndex];
		if (!spec) return;
		// Scope to the same models /model shows (settings.json enabledModels),
		// out of the authed models. Falls back to all available if unscoped.
		const available = scopeModels(ctx.modelRegistry.getAvailable());
		const current = getRoleValue(spec.role);
		const options: string[] = [AUTO_LABEL];
		const keys: (string | undefined)[] = [undefined];
		// Provider-first layout: "[provider] model-id", with the provider column
		// padded so model ids line up for easy scanning.
		const providerWidth = available.reduce((w: number, m: any) => Math.max(w, m.provider.length), 0);
		for (const m of available) {
			const key = `${m.provider}/${m.id}`;
			const marker = key === current ? " ✓" : "";
			const provider = `[${m.provider}]`.padEnd(providerWidth + 2);
			options.push(`${provider} ${m.id}${marker}`);
			keys.push(key);
		}
		const title = `${spec.label}  (current: ${current})`;
		const choice = await ctx.ui.select(title, options);
		if (choice === undefined) return; // cancelled
		const index = options.indexOf(choice);
		if (index < 0) return;
		setRoleValue(spec.role, keys[index]);
		const nowValue = keys[index] ?? "auto";
		ctx.ui.notify(`${spec.label} set to ${nowValue}`, "info");
	}

	async function openConfigMenu(ctx: any): Promise<void> {
		const recapsRow = `Session recaps: ${enabled ? "on" : "off"}`;
		const roleRows = ROLE_SPECS.map((s) => `${s.label}: ${getRoleValue(s.role)}`);
		const options = [recapsRow, ...roleRows];
		const choice = await ctx.ui.select("Pi config", options);
		if (choice === undefined) return;
		const index = options.indexOf(choice);
		if (index === 0) {
			enabled = !enabled;
			pi.appendEntry("recap-config", { enabled });
			ctx.ui.notify(`Session recaps ${enabled ? "enabled" : "disabled"}`, "info");
			return;
		}
		await pickModelForRole(index - 1, ctx);
	}

	pi.registerCommand("config", {
		description: "Open Pi config (recaps toggle + model roles). Or: /config recaps on|off",
		handler: async (args, ctx) => {
			const [key, val] = args.trim().toLowerCase().split(/\s+/);
			if (!key) {
				if (ctx.hasUI) {
					await openConfigMenu(ctx);
				} else {
					const rows = ROLE_SPECS.map((s) => `  ${s.label}: ${getRoleValue(s.role)}`).join("\n");
					ctx.ui.notify(`Recaps: ${enabled ? "on" : "off"}\n${rows}`, "info");
				}
				return;
			}
			if (key === "recaps") {
				if (val === "on" || val === "off") {
					enabled = val === "on";
					pi.appendEntry("recap-config", { enabled });
					ctx.ui.notify(`Session recaps ${enabled ? "enabled" : "disabled"}`, "info");
				} else {
					ctx.ui.notify(
						`Recaps are ${enabled ? "on" : "off"}. Use /config recaps on|off to toggle.`,
						"info",
					);
				}
				return;
			}
			// Allow /config <role> to jump straight to that role's picker.
			const roleIndex = ROLE_SPECS.findIndex((s) => s.role === key);
			if (roleIndex >= 0 && ctx.hasUI) {
				await pickModelForRole(roleIndex, ctx);
				return;
			}
			const roleNames = ROLE_SPECS.map((s) => s.role).join(", ");
			ctx.ui.notify(`Usage: /config (menu), /config recaps on|off, or /config <${roleNames}>`, "info");
		},
	});
}
